### ISSUE TITLE
Tracking for web support

### ISSUE THREAD

**Issue by RossComputerGuy** [PhantomUIx/core#8]
This issue will be used to track the necessary tasks which will be needed to make PhantomUI compatible with the web in core.

- [ ] Add support for an "anytype" scene target
- [ ] Add component node which will be used to interface with web components
- [ ] Nodes should be able to get parent and node tree needs navigation methods
